### UPDATE request to update a patients information

PUT localhost:4004/members/123e4567-e89b-12d3-a456-426614174000
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Example Name",
  "email": "john.doe@example.com",
  "address": "123 main street",
  "dateOfBirth": "1995-10-10"
}


###